In [1]:
%matplotlib inline
projecttitle = 'Analogy'
import sys, os
if sys.platform == 'darwin':
    
    sys.path.append(os.path.join("/Users", "njchiang", "GitHub", "task-fmri-utils"))
else:
    sys.path.append(os.path.join("D:\\", "GitHub", "task-fmri-utils"))

In [2]:
from fmri_core import analysis as pa
from fmri_core import utils as pu
import numpy as np
import matplotlib.pyplot as plt

In [4]:
os.chdir("D:\\CloudStation\\Grad\\Research\\montilab-ucla")
projectSettings = pu.loadConfig(os.path.join('analogy', 'config', 'project.json'))
analysisSettings = pu.loadConfig(os.path.join('analogy', 'config', 'analyses.json'))
# paths = projectSettings['filepaths']['osxPaths']
paths = projectSettings['filepaths']['winPaths']
analysisSettings['searchlight']

Loading JSON config from analogy\config\project.json
Loading JSON config from analogy\config\analyses.json


{'n_jobs': -1, 'process_mask_img': None, 'radius': 5, 'verbose': 0}

In [5]:
maskFile = "aal-LOFC-bin_mask.nii.gz"

In [7]:
sub="sub-01"
mask = pu.loadImg(os.path.join(paths['root'],
                            'derivatives',
                            sub, 'masks',
                            maskFile))

Reading file from: D:\fmri\Analogy\derivatives\sub-01\masks\aal-LOFC-bin_mask.nii.gz


In [21]:
unmasked = pu.unmaskImg(np.arange(mask.get_data().sum())+1, mask)

unmasking image...


In [20]:
mask.get_data().sum()

7551.0

In [22]:
unmasked.shape

(104, 104, 60)

In [25]:
unmasked.get_data().sum()

28512576.0

In [27]:
np.sum(np.arange(mask.get_data().sum()+1))

28512576.0

In [29]:
np.arange(mask.get_data().sum())+1

array([  1.00000000e+00,   2.00000000e+00,   3.00000000e+00, ...,
         7.54900000e+03,   7.55000000e+03,   7.55100000e+03])

In [30]:
104*104*60

648960

In [73]:
for sub in projectSettings["subjects"].keys():
    mask = pu.loadImg(os.path.join(paths['root'],
                                'derivatives',
                                sub, 'masks',
                                maskFile))
    unmasked = pu.unmaskImg(np.arange(mask.get_data().sum())+1, mask)
    coords = np.vstack([np.argwhere(dat==i)+1 for i in 
                        range(1, int(mask.get_data().sum())+1)])
    coordmat = np.hstack([np.arange(1, mask.get_data().sum()+1)[:, np.newaxis], 
                          coords]).astype(int)
    pu.save_mat_data("D:\\Downloads\\{}_locations.mat".format(sub), 
                     data=unmasked.get_data(), coords=coordmat)

Reading file from: D:\fmri\Analogy\derivatives\sub-01\masks\aal-LOFC-bin_mask.nii.gz
unmasking image...
Saving mat data to D:\Downloads\sub-01_locations.mat
Reading file from: D:\fmri\Analogy\derivatives\sub-02\masks\aal-LOFC-bin_mask.nii.gz
unmasking image...
Saving mat data to D:\Downloads\sub-02_locations.mat
Reading file from: D:\fmri\Analogy\derivatives\sub-03\masks\aal-LOFC-bin_mask.nii.gz
unmasking image...
Saving mat data to D:\Downloads\sub-03_locations.mat
Reading file from: D:\fmri\Analogy\derivatives\sub-04\masks\aal-LOFC-bin_mask.nii.gz
unmasking image...
Saving mat data to D:\Downloads\sub-04_locations.mat
Reading file from: D:\fmri\Analogy\derivatives\sub-05\masks\aal-LOFC-bin_mask.nii.gz
unmasking image...


ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [38]:
unmasked

In [39]:
dat = unmasked.get_data()

In [46]:
np.hstack(np.argwhere(dat==1)+1])

ValueError: all the input arrays must have same number of dimensions

In [56]:
coords = [np.argwhere(dat==i)+1 for i in range(1, int(mask.get_data().sum())+1)]

In [59]:
np.vstack(coords)

array([[61, 73, 15],
       [61, 73, 35],
       [61, 73, 36],
       ..., 
       [82, 70, 30],
       [82, 71, 28],
       [82, 71, 29]], dtype=int64)

In [61]:
coords = np.vstack([np.argwhere(dat==i)+1 for i in 
                        range(1, int(mask.get_data().sum())+1)])
coordmat = np.hstack([np.arange(1, mask.get_data().sum()+1)[:, np.newaxis, coords])

ValueError: all the input arrays must have same number of dimensions

In [62]:
np.arange(1, mask.get_data().sum()+1).shape

(8923,)

In [68]:
coordmat = np.hstack([np.arange(1, mask.get_data().sum()+1)[:, np.newaxis], coords]).idea

AttributeError: 'numpy.ndarray' object has no attribute 'idea'

In [70]:
coords = np.vstack([np.argwhere(dat==i)+1 for i in 
                    range(1, int(mask.get_data().sum())+1)])
coordmat = np.hstack([np.arange(1, mask.get_data().sum()+1)[:, np.newaxis], 
                      coords]).astype(int)

In [71]:
coordmat

array([[   1,   61,   73,   15],
       [   2,   61,   73,   35],
       [   3,   61,   73,   36],
       ..., 
       [8921,   82,   70,   30],
       [8922,   82,   71,   28],
       [8923,   82,   71,   29]])